### ISSUE TITLE
关于Redis

### ISSUE THREAD

**Issue by harudaee** [wenjunnie/seckill#1]
请问，Redis需要安装在哪一台服务器上：Nginx, ApplicationServer1, ApplicationServer2 还是数据库服务器

**Comment by wenjunnie** [comment]
我之前是放在数据库服务器，不过目前代码中是把后端工程和数据库都放在一个服务器上。这方面的话只要改一下配置文件中的Redis IP地址即可。

**Comment by wenjunnie** [comment]
> 请问，Redis需要安装在哪一台服务器上：Nginx, ApplicationServer1, ApplicationServer2 还是数据库服务器

我之前是放在数据库服务器，不过目前代码中是把后端工程和数据库都放在一个服务器上。这方面的话只要改一下配置文件中的Redis IP地址即可。
